version: '3.8'
services:
  envoy:
    build: 
      context: .
      dockerfile: Cargo-build.dockerfile
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    hostname: envoy
    ports:
      - "10000:10000"
      - "9901:9901"
    volumes:
      - ./target:/build/target
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - envoymesh
    cpus: 1
    command:
    - envoy
    - -c
    - /etc/envoy/envoy.yaml
    - --concurrency
    - "1"
    - --log-level
    - debug

  echologger:
    image: moesif.azurecr.io/echologger:test
    ports:
      - "8080:8080"
    networks:
      - envoymesh

networks:
  envoymesh:
