services:
  envoy:
    image: envoyproxy/envoy:v1.25.6
    hostname: envoy
    ports:
      - "10000:10000"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./target/wasm32-wasi/debug:/etc/envoy/proxy-wasm-plugins
    networks:
      - envoymesh
    cpus: 1
    command:
    - envoy
    - -c
    - /etc/envoy/envoy.yaml
    - --concurrency
    - "1"
    - --log-level
    - debug

  echo:
    build: /home/brian/Code/echologger
    image: echologger:latest
    ports:
      - 5678:80
    environment:
      PORT: 80
    networks:
      - envoymesh

networks:
  envoymesh:
