version: '3.8'
services:
  envoy:
    build: 
      context: .
      dockerfile: Cargo-build.dockerfile
    ports:
      - "10000:10000"
      - "9901:9901"
    networks:
      - envoymesh
    command:
    - envoy
    - -c
    - /etc/envoy/envoy.yaml
    - --concurrency
    - "1"
    - --log-level
    - debug

  echologger:
    image: moesif.azurecr.io/echologger:test
    ports:
      - "8080:8080"
    networks:
      - envoymesh

networks:
  envoymesh:
