services:
  envoy:
    image: envoyproxy/envoy:v1.25.6
    hostname: envoy
    ports:
      - "10000:10000"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./target/wasm32-wasi/release:/etc/envoy/proxy-wasm-plugins
    networks:
      - envoymesh
    cpus: 1

  echo:
    image: hashicorp/http-echo
    command: ["-text=Hello from echo service"]
    ports:
      - "5678:5678"
    networks:
      - envoymesh

networks:
  envoymesh:
