# This file is used to configure Istio to allow traffic to Moesif API
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: moesif-api
spec:
  hosts:
  - api.moesif.net
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
# Istio uses mTLS by default, but Moesif API does not support mTLS
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: moesif-api
spec:
  host: api.moesif.net
  trafficPolicy:
    tls:
      mode: DISABLE
