apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: moesif-plugin
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      istio: ingress
  url: oci://webassemblyhub.io/brian_moesif/moesif_api_envoy_filter:v0.2.0
  imagePullPolicy: IfNotPresent
  phase: AUTHZ
  priority: 10
  pluginConfig:
    moesif_application_id: eyJhcHAiOiIxMzI6Mzc3IiwidmVyIjoiMi4wIiwib3JnIjoiODg6MjEwIiwiaWF0IjoxNjg1NTc3NjAwfQ.ovxETFvEFypjQYLQvhn5CZms0zSp4gyya1GQ_7h32Xc
    user_id_header: X-User-Example-Header
    company_id_header: X-Company-Example-Header
    upstream: moesif-api