# This file is used to configure Istio to allow traffic to Moesif API
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: moesif
spec:
  hosts:
  - api.moesif.net
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  - number: 80
    name: http
    protocol: HTTP
  location: MESH_EXTERNAL
  resolution: DNS

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: moesif-virtual-service
spec:
  hosts:
  - api.moesif.net
  http:
  - match:
    - uri:
        exact: /moesif
    - route:
      - destination:
          host: api.moesif.net
          port:
            number: 443
      - destination:
          host: api.moesif.net
          port:
            number: 80
---
# Istio uses mTLS by default, but Moesif API does not support mTLS
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: moesif
  namespace: istio-ingress
spec:
  host: api.moesif.net
  trafficPolicy:
    tls:
      mode: DISABLE  # This disables TLS for all ports
  subsets:
    - name: http
      trafficPolicy:
        portLevelSettings:
          - port:
              number: 80
            tls:
              mode: DISABLE
    - name: https
      trafficPolicy:
        portLevelSettings:
          - port:
              number: 443
            tls:
              mode: SIMPLE  # This allows TLS for port 443
