apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: moesif-plugin
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      istio: ingress
  url: oci://moesiftest.azurecr.io/moesif-envoy-wasm-plugin:latest
  imagePullPolicy: Always
  imagePullSecret: regcred
  phase: AUTHZ
  priority: 10
  pluginConfig:
    moesif_application_id: <YOUR MOESIF APPLICATION ID>
    user_id_header: X-User-Example-Header
    company_id_header: X-Company-Example-Header
    upstream: outbound|443||api.moesif.net
    debug: true
